### ISSUE TITLE
`parse` function with `ParseOptions` argument has incorrect declared return type 

### ISSUE THREAD

**Issue by gthb** [oguimbal/pgsql-ast-parser#108]
I noticed that if you pass an `ParseOptions` argument with an `entry` to `parse()`, it will return a single AST node, not an array of them:
```ts
    // always return an array of statements.
    if (!entry && !Array.isArray(parsed)) {
        parsed = [parsed]
```

That makes the return type for that overload incorrect:
```ts
export function parse(sql: string, options?: ParseOptions): Statement[];
```
... so usage with an options argument raises a type check violation in my code:
```ts
    const parsedQuery = parse(queryWithFrom, { entry: 'selection' });
    if (parsedQuery.type !== 'select') {
        ...
```
... saying `Property 'type' does not exist on type 'Statement[]'` (but this call _will_ return a single AST node)

The overload signature should be:
```ts
export function parse(sql: string, options?: ParseOptions): any;
```
(or else something like `Statement[] | AstNode` I guess, if there's a union type like `AstNode` somewhere...)

In the same way, `parseWithComments` should have its `ast` return type attribute typed as `any` (or `Statement[] | AstNode`):
```ts
export function parseWithComments(sql: string, options?: ParseOptions): { ast: any; comments: PGComment[] } {
    return trackingComments(() => parse(sql, options));
}
```
or else it should have overloads like the `parse` function does.

**Comment by oguimbal** [comment]
Should be fixed in ` pgsql-ast-parser@11.0.0`
