### ISSUE TITLE
Typing: schema missing in From

### ISSUE THREAD

**Issue by eddieajau** [oguimbal/pgsql-ast-parser#11]
Using version `pgsql-ast-parser@^4.1.8`

Example SQL that includes a schema:

```
SELECT * from private.tbl
```

Example parsed AST:

```
{
  "columns": [
    {
      "expr": {
        "type": "ref",
        "name": "*"
      }
    }
  ],
  "from": [
    {
      "type": "table",
      "name": "tbl",
      "schema": "private"
    }
  ],
  "where": null,
  "type": "select"
}
```

Example Typescript:

```
const ast = parseFirst(sql);

if (ast.from.some((v) => v.schema !== void 0)) {
  throw new Error('schema not permitted');
}
```

Typescript reports: `Property 'schema' does not exist on type 'From'.`

Hope this helps. Great little library.

**Comment by oguimbal** [comment]
Hi !

That is because a `ast` is not guaranteed to be a table selection (it could be something else), so the types reflect that.

I guess you could do something like this:
```typescript
const ast = parseFirst(sql);

if (ast.type === 'select' && ast.from.some((v) => v.schema !== void 0)) {
  throw new Error('schema not permitted');
}
```

That said, the piece of code you are using only ensures that the top level select doesnt use a schema, but subselects could.
If you really want to ensure no table with schema is ever refered to, you should use something like that:

```typescript
astVisitor(v => ({
    tableRef: t => {
        if (t.schema)  {
            throw new Error('schema not permitted');
        }
    },
})).statement(ast);
```
...which will catch all table references. But it still will not catch other schema references such as scoped function calls, etc.

**Comment by eddieajau** [comment]
@oguimbal thanks for the suggest. That's much nicer than the recursive function I wrote to search for a "from" :)

The use case is that a customer can write their own query on their own data. Each customer is separated into their own schema, hence the need to prevent them from snooping around other customers, or the core schema tables.

**Comment by oguimbal** [comment]
Haha I see :)

For the record, `astVisitor` allows you to visit some parts you're interested in. Bu you can also modify those part on the fly using [astMapper](https://github.com/oguimbal/pgsql-ast-parser#-modifying-sql-ast)

... which could be useful, if for instance you'd like to automatically transform statements like `SELECT * FROM data WHERE xxx`  to `SELECT * FROM data WHERE customer_id='whatever' AND xxx`

**Comment by oguimbal** [comment]
Ah, and for the record, I'm currently working on [pg-server](https://github.com/oguimbal/pg-server) which should even allow to expose postgres database directly to your customers (using the "proxy" functionality of pg-server), and transform the statements they execute without them noticing !

(and its almost finished)
