### ISSUE TITLE
Operators @@ is not supported by the parser

### ISSUE THREAD

**Issue by MatthieuVegreville** [oguimbal/pgsql-ast-parser#116]
Hello Olivier,

Hope you're doing well. We're getting back to the project of fully pushing in-memory database for the Greenly project. Right now, the definition of operators is restrictive in the lexer compared to SQL definition and doesn't support the operator @@ that we use with the methods to_tsvector and ts_query for example.
Do you think you could add it?

Thanks,
Matt

Also: we'd like to support the project once we can confirm we can use it in our env!

**Comment by oguimbal** [comment]
Hi !
Fixed in `pgsql-ast-parser@11.0.1`.

I'll update pg-mem with this version soon

**Comment by MatthieuVegreville** [comment]
awesome!
