### ISSUE TITLE
Support for VIEWS

### ISSUE THREAD

**Issue by gabssnake** [oguimbal/pgsql-ast-parser#13]
Hello oguimbal,
Wanted to create some views but stumbled upon this error.
Guess this simply means they are not supported for now?
Cheers,

```sql
CREATE VIEW example AS SELECT 1;
```

```
👉 Failed query:
    CREATE VIEW example AS SELECT 1;;

💀 Syntax error at line 1 col 13:
  CREATE VIEW example
              ^
Unexpected word token: "example". I did not expect any more input. Here is the state of my parse table:
    kw_index → %word ● 
    kw_sequence → %word ● 
    kw_temporary → %word ● 
    kw_temp → %word ● 
    kw_extension → %word ● 
    kw_type → %word ●
```

**Comment by oguimbal** [comment]
Hi !
[That's planned](https://github.com/oguimbal/pg-mem/issues/34) :)

**Comment by gabssnake** [comment]
Awesome !

**Comment by oguimbal** [comment]
Since this is now supported by the parser (not yet by pg-mem), I'll close this issue... feel free to subscribe to https://github.com/oguimbal/pg-mem/issues/34 to be notified !
