### ISSUE TITLE
Prepared statements

### ISSUE THREAD

**Issue by mmkal** [oguimbal/pgsql-ast-parser#2]
Hi again!

One feature that'd be really useful would be the ability to parse prepared statements. i.e. either a full, valid prepared statement:

```sql
prepare mystatement as select * from information_schema.columns where table_name = $1
```

Or maybe a custom mode that knows to look out for `$1`, `$2` etc.

```sql
select * from information_schema.columns where table_name = $1
```

I think the former would be preferable as it's valid SQL, whereas the latter only makes sense in certain contexts.

The use case would be reading a SQL file and generating a strongly-typed function for it. An alternative right now is to regex-swap `/\$\d+` into `'placeholder'` or something, to at least get valid syntax. But that can easily go wrong if there are commented-out or quoted `$1`s, etc.

**Comment by oguimbal** [comment]
Done in 3.1.0 !
