### ISSUE TITLE
Parsing comments (not the COMMENT statement, but /* comments */)

### ISSUE THREAD

**Issue by benjie** [oguimbal/pgsql-ast-parser#23]
Hey; really great to have another JS PostgreSQL parser and what you're doing with pg-mem looks amazing!

As you probably know the PostgreSQL parser treats comments (`/* ... /* ... */ ... */` and `-- until end of line`) as whitespace, and I'm assuming (from glancing at your tests) that this project does too. Would there be any interest in having this parser support including comments in the AST, or (since it's primarily to power pg-mem, which does not need this functionality) is that out of scope?

Context: https://github.com/benjie/prettier-plugin-pg/issues/10#issuecomment-701675765

(If you want to discuss this out-of-band, you can reach me via [the Graphile discord](https://discord.gg/graphile) or [Twitter DM @benjie](https://twitter.com/benjie).)

**Comment by benjie** [comment]
(One of the other issues with the PostgreSQL parser is it contains absolutely minimal location information (basically just enough for the error messages and no more) which makes it extremely challenging to reattach comments in the right places at a later stage; [more context here](https://github.com/benjie/prettier-plugin-pg/issues/5).)

**Comment by oguimbal** [comment]
Fixed with `pgsql-ast-parser@6.0.0` , see [FAQ](https://github.com/oguimbal/pgsql-ast-parser#faq)
