### ISSUE TITLE
Unsupported OFFSET qparam token?

### ISSUE THREAD

**Issue by morgothulhu** [oguimbal/pgsql-ast-parser#29]
Thanks again for fixing #20 and #21 - now I see a new error with `6.3.2`

### Error message:

```
Unexpected qparam token: "$2". Instead, I was expecting to see one of the following:

    - A "int" token
```

### Query

```
SELECT foo FROM bar WHERE "isEnabled" = $1 OFFSET $2
```

args: `[true,0]`

**Comment by oguimbal** [comment]
Ah ! Right. Thanks, I will fix it asap.

**Comment by oguimbal** [comment]
Should be ok with `pgsql-ast-parser@7.0.0` 🎉
