### ISSUE TITLE
Select from function

### ISSUE THREAD

**Issue by mmkal** [oguimbal/pgsql-ast-parser#3]
Hi - thanks so much for the super-fast responses/fixes. I found another edge case which isn't handled:

```sql
select * from concat('a', 'b')
```

👆 that fails but this succeeds 👇 

```sql
select concat('a', 'b')
```

In this particular case the workaround `select concat('a', 'b')` is fine, but when it's a custom function which returns a `type` the function can be used like a table: `select x, y from myfunc('foo')`

**Comment by oguimbal** [comment]
Yup, that's because this parser was built around [pg-mem](https://github.com/oguimbal/pg-mem) needs, which does not support it yet.

Maybe that's a good occasion to implement it. I'll  look into it asap.

**Comment by oguimbal** [comment]
Implemented in  `pgsql-ast-parser@4.0.1` 

(not yet implemented in [pg-mem](https://github.com/oguimbal/pg-mem), though... but if you only use `pgsql-ast-parser`, its done)
