### ISSUE TITLE
Unsupported `BEGIN` syntax

### ISSUE THREAD

**Issue by benjie** [oguimbal/pgsql-ast-parser#31]
`begin deferrable` and `begin isolation level serializable` fail to parse; docs:

https://www.postgresql.org/docs/current/sql-begin.html

:heart:

**Comment by oguimbal** [comment]
Fixed with `pgsql-ast-parser@7.1.0` ! Sorry for the delay, I have a lot on my plate these days 😏

**Comment by benjie** [comment]
No worries! Thanks for the fix 👍
