### ISSUE TITLE
WITH RECURSIVE my_func error

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [oguimbal/pgsql-ast-parser#33]
When writing a recursive function starting with 
`WITH RECURSIVE my_func() as ()`

I'll get the following error

```
>  Unexpected word token: "my_func". Instead, I was expecting to see one of the following:
> 
>      - A "kw_as" token
```

 
Postgres documentation for this feature: https://www.postgresql.org/docs/9.1/queries-with.html 
https://www.postgresqltutorial.com/postgresql-recursive-query/

**Comment by BrandiATMuhkuh** [comment]
Is there a way I can contribute? I saw you use a DSL for the parser, but I don't have the expertise on how to use it.

**Comment by oguimbal** [comment]
Hi, it's coming soon !

Incidentally, your request has lead me to a non trivial refactoring... thus the delay :)

**Comment by BrandiATMuhkuh** [comment]
I see. Thanks man. I'm not surprised. A DSL that can handle recursion is surely not trivial! Thanks!

**Comment by oguimbal** [comment]
Hi ! 

Fixed in `pgsql-ast-parser@8.1.0` (finally !)

See [breaking changes](https://github.com/oguimbal/pgsql-ast-parser/discussions/43)  with the 8.0.0 major release.

Sorry for the delay :)

**Comment by BrandiATMuhkuh** [comment]
Awesome. I'll give it a go tomorrow. 
No need to say sorry. You are duing this for free for us. I'm super thankful for what you do!

**Comment by BrandiATMuhkuh** [comment]
Sorry, It took me longer then expected. I found an issue related to the RECURSIVE function. I made the following issue for it https://github.com/oguimbal/pgsql-ast-parser/issues/44
