### ISSUE TITLE
[Safari] Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by choco** [oguimbal/pgsql-ast-parser#34]
I'm trying the library int he browser but it seems that a bunch of the regexes are not compatible with Safari and I get the error above while trying to load the package.

**Comment by oguimbal** [comment]
Ouch. 
Yes, there are quite a lot of lookbehind expressions in [the lexer](https://github.com/oguimbal/pgsql-ast-parser/blob/master/src/lexer.ts), and it would seem that [Safari doesnt like them](https://caniuse.com/js-regexp-lookbehind).

The lexer is a very sensitive thing: Changing it significantly could mean rewriting the parser significantly, and  I have no real idea how to stop using lookbehinds without doing that 😶

So I acklowledge this issue to be a thing (and I will mention it in the readme). 
But to be honnest, browser compatibility not really being a priority to me, I am very usure wether if I will consider fixing it anytime soon 😯
... This issue might resolve itself when Safari implements lookbehinds.

PR are open if someone sees a trick, or wants to tackle the problem.

**Comment by ArniDagur** [comment]
I opened a PR in https://github.com/oguimbal/pgsql-ast-parser/pull/112
