### ISSUE TITLE
Type aliases are quoted causing invalid output

### ISSUE THREAD

**Issue by corinv** [oguimbal/pgsql-ast-parser#38]
Sorry for bombarding you with issues, I'm running some rather hefty queries through the parser so I guess I'm likely to pick up a few issues.

Example valid query:

`select '1'::integer`

Once parsed, the output from SQL from `toSql` is:

`SELECT (('1')::"integer" )`

which when evaluated will throw:

`ERROR:  type "integer" does not exist`

From some digging I can see this is due to the fact that `integer` is alias for an actual (internal) type `int4`, of which the internal type replaces the alias at parse time. Double quoting this however prevents that processing, and there is not an actual `integer` type. (Discussed here https://stackoverflow.com/questions/30617764/postgresql-double-quoted-type)

This is not just exclusive to integer, there are plenty of aliases used as shown here: https://www.postgresql.org/docs/13/datatype.html#DATATYPE-TABLE

It seems the above list is not exhaustive however.

Since quoting types is important for custom types, I'm guessing the solution to this would be to determine a whitelist of aliases which will not be double quoted during when being output by `toSql`. 

Might be able to contribute in determining that list, but I'm not really familiar with postgres at this low a level.

**Comment by oguimbal** [comment]
Arg.

Like with #35, the double-quoting thing was the lazy way of being safe.

I think here that the good solution is to remove the systematic double quoting, except if either:

- The type name does not match `/^\w+$/`
- The type name is [a keyword](https://github.com/oguimbal/pgsql-ast-parser/blob/master/src/keywords.ts)

I will do that asap !
(You can create a PR if its urgent for you, I'll publish it)

**Comment by oguimbal** [comment]
Some more details: That seems to be almost right. The parser behaves like that:

- `select 42::precision`  👉 syntax error (`precision` is a keyword)
- `select 42::whatever`  👉 type "whatever" does not exist

... which matches the rules I mentioned earlier. However, things start to be a bit more twisted when involving types with spaces:

- `select 42::double precision;` 👉 OK
- `select 42::"double precision";` 👉  type "double precision" does not exist

.. and given `create type "ab cd" as enum('a');` 
- `select 'a'::ab cd`  👉  type "ab" does not exist
- `select 'a'::"ab cd"` 👉 OK


.... so a good enough rule should be a bit more complicated... something like (not tested):

```typescript
const kwSet = new Set(keywords.map(x => x.toLowerCase());
function shouldQuote(typeName: string) {
   if (typeName.toLowerCase() !== typeName) {
       return true;
   }
   const words = typeName.split(/\s+/g);
   if (!kwSet.has(words[0])) {
       return true;
   }
   return words.slice(1).some(x => !kwSet .has(x));
}
```

**Comment by corinv** [comment]
I tested your proposed fix with a bit of tweaking.

These types can't be added to the keywords list without some other changes, since the parser uses that list for various things, a handful of tests break on adding a few datatypes to that list. So instead I created a separate list of type aliases (I don't think "regular" types (datatypes whose name correspond to their internal datatype's name) are affected) and used that list instead, and scoped the quoting logic to just the datatype output.

After the above, the fix appears to work great. 

I'm happy to tidy up my tweaked version, write a couple of tests and put it up as a PR, though I would need to source a list of these aliases (or I could probably just use a list of all types, as the quoting shouldn't matter on "regular" types), since I've only been using a couple for testing purposes. However if you think this can be fixed with a wider change to quoting then it might be cleaner if this is just encompassed by that.

**Comment by oguimbal** [comment]
Hi ! Oh sorry I forgot to tell you, but [I ended up implementing a fix](https://github.com/oguimbal/pgsql-ast-parser/commit/2b4cdbd6866a710eccde9fcd7a8f511591f35a99) 😅

It turned out to be a bit more complicated than I anticipated, and given that the typenames which have a space are quite few, it was simpler to hardcode them.

**Comment by corinv** [comment]
Awesome, just gave it a spin and it works perfectly. Any chance it will be published soon?

My solution was a lot hackier looking than that, so no worries :grin:.

Thanks again work on this library!

**Comment by oguimbal** [comment]
🙏 thanks, my pleasure.

👉  `pgsql-ast-parser@7.2.0`
