### ISSUE TITLE
Using toSql, single character refs are quoted, multicharacter are not.

### ISSUE THREAD

**Issue by g2network** [oguimbal/pgsql-ast-parser#39]
Testing toSql functionality under version 7.2.0, the application of double quotes to object refs in toSql output is changed considerably and, for my purposes, for the better. 

However, any ref (tablename, table alias, column name, column alias) that is a single character in the actual SQL, is double quoted in the toSql output, while a multicharacter ref is output without quotes. 

Presume this isn't intended behavior. 

Input SQL:

SELECT aa.id, aa.r, aa.content
    FROM docs aa
    INNER JOIN (
        SELECT id, MAX(rev) rev
        FROM docs
        GROUP BY id
    ) b ON aa.id = b.id AND aa.rev = b.rev;

toSQL output:

SELECT aa .id , aa ."r" , aa .content  
    FROM docs  AS aa 
   INNER JOIN (
      SELECT id , (max (rev) ) AS rev  
      FROM docs   
      GROUP BY id 
   )  AS "b" ON ((aa .id = "b" .id) AND (aa .rev = "b" .rev))

**Comment by oguimbal** [comment]
Indeed, it is not 😁

Fixed in `pgsql-ast-parser@7.2.1`

Thanks for the report !

**Comment by g2network** [comment]
Thank you kindly.

g2
