### ISSUE TITLE
Arbitrary Precision Numbers

### ISSUE THREAD

**Issue by zapplebee** [oguimbal/pgsql-ast-parser#4]
When parsing numeric types with arbitrary precision, the parser expects a parenthesis instead of the valid syntax of a comma.

```typescript
import { parse, Statement } from "pgsql-ast-parser";

const ast: Statement[] = parse(`
CREATE TABLE foo (
    id integer NOT NULL,
    size numeric(10,2) NOT NULL
`);
```

```
Error: Syntax error at line 4 col 20:

      size numeric(10,
                     ^
Unexpected comma token: ",". Instead, I was expecting to see one of the following:

    - A "rparen" token
```
The postgres docs outlining this signature:
https://www.postgresql.org/docs/9.1/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL

**Comment by oguimbal** [comment]
Fixed in `pgsql-ast-parser@4.0.0` 🙂

(not yet implemented in [pg-mem](https://github.com/oguimbal/pg-mem), though... but if you only use `pgsql-ast-parser`, its done)

Thanks for the feedback
