### ISSUE TITLE
Setup development

### ISSUE THREAD

**Issue by RafaelGSS** [oguimbal/pgsql-ast-parser#40]
Hey!

I'm trying to set up the development environment for this project in order to make some changes but I got an error when I run the tests, perhaps is missing something in _README_?

Steps:

- Clone project
- `npm i`
- `npm run test`

```sh
npm run test

> pgsql-ast-parser@7.2.1 test pgsql-ast-parser
> mochapack src/**/*.spec.ts

 WEBPACK  Compiling...

  [===                      ] 13% (building)Parsing nearley pgsql-ast-parser/src/syntax/main.ne
Parsing nearley pgsql-ast-parser/src/literal-syntaxes/array.ne
Parsing nearley pgsql-ast-parser/src/literal-syntaxes/geometric.ne
  [====                     ] 14% (building)Parsing nearley pgsql-ast-parser/src/literal-syntaxes/interval.ne
Parsing nearley pgsql-ast-parser/src/literal-syntaxes/interval-iso.ne
  [=========================] 100% (completed)

 WEBPACK  Failed to compile with 1 error(s)

Error in pgsql-ast-parser/src/syntax/main.ne.ts

  [tsl] ERROR in pgsql-ast-parser/src/syntax/main.ne.ts(619,13)
        TS1135: Argument expression expected.
```

**Comment by oguimbal** [comment]
Hi !

Sorry for the delay, I have a lot on my plate these days.

That's bad luck... I pushed something broken, which is work-in-progress (I usually dont do that, I dont know why I pushed it).

You can start from commit 3bd2a695f2ce0d17c17f7400793b6bd39ba451c1  (the 7.2.1 tag), for which everything should be fine !
