### ISSUE TITLE
Support `restart identity`

### ISSUE THREAD

**Issue by RafaelGSS** [oguimbal/pgsql-ast-parser#41]
Hey!

I'm using `knex` to create some migrations and at the end of the flow, usually, there are calls to `truncate` the tables like:

```sql
truncate "example_table" restart identity;
```

However, currently, this library doesn't support `restart identity`. I'd like to help you add that feature when #40 is solved

**Comment by oguimbal** [comment]
Hi again 😁

Thanks for that !

That's actually a very nice issue for a first contributor 👍

I recommand to read [this](https://github.com/oguimbal/pg-mem/blob/master/CONTRIBUTING.md#a-implement-its-parser) if you want to know where to start.

FYI the parsing expression of `truncate` is [here](https://github.com/oguimbal/pgsql-ast-parser/blob/3bd2a695f2ce0d17c17f7400793b6bd39ba451c1/src/syntax/delete.ne#L31-L34), and the unit tests for it are [there](https://github.com/oguimbal/pgsql-ast-parser/blob/3bd2a695f2ce0d17c17f7400793b6bd39ba451c1/src/syntax/delete.spec.ts#L19-L27) ... currently a pretty trivial statement !
