### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by timneedham** [oguimbal/pgsql-ast-parser#50]
Hi!

**First of all, incredible project! Love it! :heart:**

One thing... add support for nested block comments?

This currently fails, and is apparently [valid in the SQL standard](https://www.postgresql.org/docs/13/sql-syntax-lexical.html#SQL-SYNTAX-COMMENTS):

``` sql
/* multiline comment
 * with nesting: /* nested block comment */
 */
```

...even Github marks this one as an error! :wink:

**Comment by timneedham** [comment]
```
  /* multiline comment
 * with nesting: /* nested block comment */
 *
                                                                 ^
Unexpected star token: "*". Instead, I was expecting to see one of the following:

    - A "semicolon" token
    - A "kw_create" token
    - A "kw_create" token
    - A "kw_create" token
    - A "kw_create" token
. . .
```

**Comment by oguimbal** [comment]
Thanks for the report, and for the kind words !

I dont see an obvious solution solution, given this comments are implemented [using a regex](https://github.com/oguimbal/pgsql-ast-parser/blob/18f7bcab3f950efcfb75ad3d921c6f464262e863/src/lexer.ts#L53-L54)

... I will have to think about it :)

**Comment by janpaepke** [comment]
Notes on the PR:
1. moved `comment` rules above store to give `*/` priority over `*` (`'star'`).
2. kept track of opening and closing tokens in lexer.next

**Important:**
This PR now breaks queries with unclosed nested comments.
The old version parsed `/* /**/ select` just fine, returning `'/* /* */ '` as the comment.
The new version will break with this query, as it keeps on looking for the second `*/`
