### ISSUE TITLE
Common Table Expression Support?

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pgsql-ast-parser#56]
I'm running `v1.9.9`

Do you support CTE queries yet?  If not I need them!!  I need to be able to efficiently do multiple inserts in one query call

I tried this, but for some odd reason it's complaining about a `;` that's not even there!

**CompanyDB.ts**
```js
async function add(company: CompanyNewInput): Promise<CompanyTable> {
	const query = `
		WITH newCompany AS (
			insert into company (
				company_id,
				company_name
			)
			values (
				${company.id},
				'${company.name}'
			)
			returning newCompany_id
		),
		newProfile AS (
			insert into profile (
				company_id,
				profile_header_image_url
			)
			values (
				newCompany_id,
				'${company.profile.header.imageUrl}'
			)
			returning profile_id as newProfileId, profileprofile_header_image_url
		),
		newCompanyProfile AS (
			insert into company_profile (
				company_id,
				profile_id
			)
			values (
				${company.id},
				newProfileId
			)
		)`;

	const addedCompany: CompanyTable = await queryDB(query, queryType.ONE);
	return addedCompany;
}
```

Here is the query sent to pg-mem when I debug:
```sql
WITH newCompany AS (
	insert into company (
		company_id,
		company_name
	)
	values (
		${company.id},
		'${company.name}'
	)
	returning newCompany_id
),
newProfile AS (
	insert into profile (
		company_id,
		profile_header_image_url
	)
	values (
		newCompany_id,
		'${company.profile.header.imageUrl}'
	)
	returning profile_id as newProfileId, profileprofile_header_image_url
),
newCompanyProfile AS (
	insert into company_profile (
		company_id,
		profile_id
	)
	values (
		${company.id},
		newProfileId
	)
)
```

**Error:** 🤷🤷🤷

```
💀 Syntax error at line 33 col 5:

  			);
      ^
Unexpected semicolon token: ";". Instead, I was expecting to see one of the following:
```

I looked at your code and saw

https://github.com/oguimbal/pg-mem/blob/master/src/schema.ts
`private buildWith(p: WithStatement): _ISelection {        throw new NotSupported('"WITH" statements');    }`

but then I see:
`private executeWith(t: _Transaction, p: WithStatement): QueryResult {`

so it looks like it's Supported?  If so I don't see why the above it complaining when there is no `;` in the sql statement sent.

**Comment by janpaepke** [comment]
Not sure this is actually a parser issue.

Maybe I am wrong, but afaik each `WITH` clause must be attached to a primary statement (`SELECT`, `INSERT`, `UPDATE`, or delete.

In fact running the query in the parser directly fails with `Unexpected end of input`.

So if anything this might be sub-optimal error-handling in pg-mem?

**Comment by oguimbal** [comment]
Yup, I did not see that the query does not include any SELECT statement.

`WITH` is supported (maybe not at the time this issue was created ?) 

Lets close this then ! thanks @janpaepke
