### ISSUE TITLE
[ALTER TABLE] Support parsing multiple alterations

### ISSUE THREAD

**Issue by TheLazyDev** [oguimbal/pgsql-ast-parser#57]
![image](https://user-images.githubusercontent.com/10905579/125792376-44f2125e-4bac-48af-a304-dcded6c9f16a.png)

I am facing this error when I try to run this query below:-

`ALTER TABLE reviews ADD COLUMN IF NOT EXISTS reviewer UUID,ADD COLUMN IF NOT EXISTS reviewee UUID,ADD COLUMN IF NOT EXISTS job_id UUID,ADD COLUMN IF NOT EXISTS review VARCHAR,ADD COLUMN IF NOT EXISTS rating FLOAT DEFAULT 0;;`

This query is working properly  when I run it through SQL runner :/

**Comment by TheLazyDev** [comment]
No problem I understand I actually liked your library because it is very configurable but sadly due to this error I can't use it in my project if you don't mind can you provide any suggestions for setting up a in memory instance of postgres because I have to write unit tests for my code and I am unable to find any usable module :/

**Comment by oguimbal** [comment]
There arent many alternatives, as far as I know.
The only other option that I know if is to use an actual postgres instance, wrapped in a transaction, or a brand new one for each test.
You can set this reliably up using Docker and running your tests against a clean dockerized db, but this has a significant overhead, and is definitely not trivial to setup.

Cant you split your alter statements in multiple single alter statements (that would be supported by pg-mem) ?

**Comment by oguimbal** [comment]
Released as [pgsql-ast-parser@9.0.0](https://github.com/oguimbal/pgsql-ast-parser/releases/tag/9.0.0), thanks to @bchelli
