### ISSUE TITLE
Missing support for type: timestamp with time zone

### ISSUE THREAD

**Issue by cyrille-arundo** [oguimbal/pgsql-ast-parser#6]
Specification: https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT

https://oguimbal.github.io/pg-mem-playground/

```
CREATE TABLE  test ("timestamp" timestamp with time zone NOT NULL);

type "timestamp with time zone" does not exist

🐜 This seems to be an execution error, which means that your request syntax seems okay,
but the resulting statement cannot be executed → Probably not a pg-mem error.

*️⃣ Failed SQL statement: CREATE TABLE  test ("timestamp" timestamp with time zone NOT NULL);;

```

**Comment by cyrille-arundo** [comment]
timestamp with time zone is implemented but for some reason, it doesn't work in the `pg-mem-playground`

**Comment by oguimbal** [comment]
Hi !

It is most likely because I added support for it recently, but forgot to publish pg-mem playground since :)

Will do.
