### ISSUE TITLE
Remove a column from list of "Insert Into" command

### ISSUE THREAD

**Issue by mnlbox** [oguimbal/pgsql-ast-parser#68]
Hi @oguimbal and thanks for this awesome library,

I have a list of Insert commands and I want to remove one specific column from my queries for example I want to remove column A and it's value from the Insert queries bellow:
```
INSERT INTO public.test (id, A, B) VALUES ('1', 'a', 'b');
INSERT INTO public.test (id, A, B) VALUES ('2', 'a2', 'b2');
```
And I want to parse and modify these queries to:
```
INSERT INTO public.test (id, B) VALUES ('1', 'b');
INSERT INTO public.test (id, B) VALUES ('2', 'b2');
```
This is my try until now:

```
const testQuery = `INSERT INTO public.test (id, A, B) VALUES ('1', 'a', 'b');
INSERT INTO public.test (id, A, B) VALUES ('2', 'a2', 'b2');`

const ast: Statement[] = parse(testQuery);

const columnMapper = astMapper((map) => ({
  insert: (i) => {
    const columnIndex = i.columns.findIndex(
      (column) => column.name === "A"
    );
    if (columnIndex !== -1) {
      i.columns.splice(columnIndex, 1);
      return i;
    }
    return map.super().insert(i);
  },
}));

const modified = columnMapper.statement(ast[1]);
console.log(toSql.statement(modified));
```

And this is my result:
```
INSERT INTO public.test (id, B) VALUES (('2'), ('a2'), ('b2'));
```

As you can see it removed column but I can't find any way to remove related value for this column (`a2`)
I don't know if it is a bug or I missed anything but values not accessible from this path `insert>insert>values`
Also values has some redundant parenthesis like this: `('2')` after using `toSql` function.

**Comment by oguimbal** [comment]
Hi !

The parser does not have any knowledge about schema, nor about coherency of instructions.
It only know about language structure.
So even if you remove a column name, there is nothing that will automatically remove the corresponding column from inserted values... that's the job [of the executor](https://github.com/oguimbal/pg-mem) to know this kind of things.

So you have to also remove the value yourself.

That said, I just fixed a small bug I found in astMapper... you will have to upgrade to `pgsql-ast-parser@9.3.1`

I think that what you are looking for is something like this:

```typescript

const testQuery = `INSERT INTO public.test (id, A, B) VALUES ('1', 'a', 'b');
                    INSERT INTO public.test (id, A, B) VALUES ('2', 'a2', 'b2');`;

const ast = parse(testQuery);

let columnIndex = -1;
const columnMapper = astMapper((map) => ({
    insert: (i) => {
        columnIndex = i.columns?.findIndex(
            c => c.name === 'a'
        ) ?? -1;
        if (columnIndex >= 0) {
            i.columns!.splice(columnIndex, 1);
        }
        return map.super().insert(i);
    },
    values: (v) => {
        if (columnIndex !== -1) {
            for (const vs of v.values)
                vs.splice(columnIndex, 1);
        }
        return map.super().values(v);
    }
}));

const modified = columnMapper.statement(ast[1]);
console.log(toSql.statement(modified));
```


As for the unnecessary parenthesis: I did not bother to implement operator precendence in the sql reconsitutions... So it always insert parenthesis around any expression. So `3*2+1` will appear as `(((3)*(2))+(1))`. 
They are unnecessary, but harmless :)
