### ISSUE TITLE
Not equal operator not working properly

### ISSUE THREAD

**Issue by jb-ashish** [oguimbal/pgsql-ast-parser#77]
sql = 'select * from ts_users WHERE ID != "test"' 
output = `{
"type": "binary",
"left": {
"type": "ref",
"name": "id"
},
"right": {
"type": "ref",
"name": "test"
},
"op": "!="
}`
`output .right.name = "test"`
this should be `output .right.value= "test"`

**Comment by oguimbal** [comment]
nope, `"test"` in postgres is a reference... if you expect a string value, then it should be `'test'`  (double quoted strings are not strings in postgres sql... they are case-sensitive identifiers 🙂)
