### ISSUE TITLE
Column name in where condition is always return  in lowercase

### ISSUE THREAD

**Issue by jb-ashish** [oguimbal/pgsql-ast-parser#80]
"select Name from ts_users WHERE Name = 'ash'"

where = 
`{
  "type": "binary",
  "left": {
    "type": "ref",
    "name": "name"
  },
  "right": {
    "type": "string",
    "value": "ash"
  },
  "op": "="
}`

**Comment by oguimbal** [comment]
that is the expected behaviour... if you dont double-quote your identifiers, then postgres will treat them as lowercase.

```sql
create table test(Name text);
```

will create a table with a column `name`

```sql
create table test("Name" text);
```
wil create a column `Name`

 => `select "Name" from ts_users WHERE Name = 'ash'`  is what you're looking for 🙂
