### ISSUE TITLE
JSONB operators

### ISSUE THREAD

**Issue by mmkal** [oguimbal/pgsql-ast-parser#9]
Hi again! I found another case not handled:

```sql
SELECT to_json(now())#>>'{}'
```

The `#>>` uses an array to extract a nested path from a jsonb object. There are some other [jsonb operators](https://stackoverflow.com/a/55387470/1002973) which I haven't tested yet with pgsql-ast-parser. But I can imagine they'd be pretty handy for pg-mem too if not supported already.

The example above specifically is a [stackoverflow](https://stackoverflow.com/a/55387470/1002973) answer of how to get the a timestamptz in ISO string format, so not too niche of a use-case, even though the syntax looks funky.

**Comment by oguimbal** [comment]
Done for `pgsql-ast-parser@4.1.8`  (to be fair, [that was an easy one](https://github.com/oguimbal/pgsql-ast-parser/commit/7721ccd664ce5a059f6178ca51b7f0cebe89901b) 😁) ... do you need it in pg-mem ? (if yes, i'll try to implement it asap, else, i'll add that in some obscure todo.txt)
