### ISSUE TITLE
Test files directly under `src` folder don't get executed

### ISSUE THREAD

**Issue by gthb** [oguimbal/pgsql-ast-parser#92]
For me (and for your CI :) ) the `npm run test` task does not execute the tests in `src/*.spec.ts` (files directly in the `src` folder), only those in its subfolders.

This appears to be because the `test` script uses `src/**/*.spec.ts` but `**` doesn't have that intended meaning in the default script-shell for npm.

Fun fact: your CI job is neglecting to run the tests in `src/*.spec.ts` because of this. :-)

**Comment by oguimbal** [comment]
I suppose this is fixed by your PR, then ?

**Comment by gthb** [comment]
> I suppose this is fixed by your PR, then ?

Yes, if I remember right :), looks like I forgot to make that explicit.

**Comment by oguimbal** [comment]
I'm closing that, then :) thanks
